Source/Emerge/Controllers/Control/AdminSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Emerge.Models;
using Emerge.Services;
using Emerge.Data;
using Emerge.Common;
using System.Web.Security;
using System.IO;



namespace Emerge.Controllers.Control
{
    public partial class ControlController : Controller
    {
       
        //
        // GET: /AdminSearch/
        [ValidateInput(false)]
       //[RequireHttps]
        public ActionResult AdminSearch()
        {
            BALCompanyUsers ObjBALCompanyUsers = new BALCompanyUsers();
            MembershipUser objMembershipUser = Membership.GetUser();
             var UserName = objMembershipUser.UserName;
             if (Roles.IsUserInRole(UserName, "SystemAdmin"))//Roles.IsUserInRole(UserName, "Admin") || 
             {
               
                 ViewBag.NewAccountContetns = "expand";
                 ViewBag.NoticeContent = "expand";
                 ViewBag.WatchListContent = "expand";
                 ViewBag.PendingReviewReportContent = "expand";
                 ViewBag.MannualReportContent = "expand";
                 ViewBag.QualityContent = "expand";
                 ViewBag.HelpWithOrdersContent = "expand";
                 ViewBag.PendingReportsContent = "expand";
                 ViewBag.IncompleteReportsContent = "expand";
                 ViewBag.DrugTestingOrdersContent = "expand";
                 ViewBag.BatchOrdersContent = "expand";
                 
             }
             else
             {
                 List<tblDashboardList> Records = ObjBALCompanyUsers.GetDashBoardStatusByUserId(Guid.Parse(objMembershipUser.ProviderUserKey.ToString()));
                 bool NewAccountContetnsDiv = Records.Where(rec=>rec.DivName == "NewAccountContetnsDiv" ).ElementAt(0).IsDivOpen;
                 if (NewAccountContetnsDiv == true)
                 {
                     ViewBag.NewAccountContetns = "expand";
                 }
                 else
                 {
                     ViewBag.NewAccountContetns = "colapse";
                 }


                 bool NoticeContentDiv = Records.Where(rec => rec.DivName == "613NoticeContentDiv").ElementAt(0).IsDivOpen;
                 if (NoticeContentDiv == true)
                 {
                     ViewBag.NoticeContent = "expand";
                 }
                 else
                 {
                     ViewBag.NoticeContentDiv = "colapse";
                 }


                 bool WatchListContentDiv = Records.Where(rec => rec.DivName == "WatchListContentDiv").ElementAt(0).IsDivOpen;
                 if (WatchListContentDiv == true)
                 {
                     ViewBag.WatchListContent = "expand";
                 }
                 else
                 {
                     ViewBag.WatchListContent = "colapse";
                 }


                 bool PendingReviewReportContentDiv = Records.Where(rec => rec.DivName == "PendingReviewReportContentDiv").ElementAt(0).IsDivOpen;
                 if (PendingReviewReportContentDiv == true)
                 {
                     ViewBag.PendingReviewReportContent = "expand";
                 }
                 else
                 {
                     ViewBag.PendingReviewReportContent = "colapse";
                 }


                 bool MannualReportContentDiv = Records.Where(rec => rec.DivName == "MannualReportContentDiv").ElementAt(0).IsDivOpen;
                 if (MannualReportContentDiv == true)
                 {
                     ViewBag.MannualReportContent = "expand";
                 }
                 else
                 {
                     ViewBag.MannualReportContent = "colapse";
                 }

                 bool QualityContentDiv = Records.Where(rec => rec.DivName == "QualityContentDiv").ElementAt(0).IsDivOpen;
                 if (QualityContentDiv == true)
                 {
                     ViewBag.QualityContent = "expand";
                 }
                 else
                 {
                     ViewBag.QualityContent = "colapse";
                 }

                 bool HelpWithOrdersContentDiv = Records.Where(rec => rec.DivName == "HelpWithOrdersContentDiv").ElementAt(0).IsDivOpen;
                 if (HelpWithOrdersContentDiv == true)
                 {
                     ViewBag.HelpWithOrdersContent = "expand";
                 }
                 else
                 {
                     ViewBag.HelpWithOrdersContent = "colapse";
                 }
                 var  IsexisitContentDiv = Records.Where(rec => rec.DivName == "BatchOrdersContentDiv").Count();
              
                 if (IsexisitContentDiv > 0)
                 {
                     bool BatchOrdersContentDiv = Records.Where(rec => rec.DivName == "BatchOrdersContentDiv").ElementAt(0).IsDivOpen;
                     if (BatchOrdersContentDiv == true)
                     {
                         ViewBag.BatchOrdersContent = "expand";
                     }
                     else
                     {
                         ViewBag.BatchOrdersContent = "colapse";
                     }
                 }
                 else
                 {
                     ViewBag.BatchOrdersContent = "expand";
 
                 }

                 bool PendingReportsContentDiv = Records.Where(rec => rec.DivName == "PendingReportsContentDiv").ElementAt(0).IsDivOpen;
                 if (PendingReportsContentDiv == true)
                 {
                     ViewBag.PendingReportsContent = "expand";
                 }
                 else
                 {
                     ViewBag.PendingReportsContent = "colapse";
                 }

                 bool IncompleteReportsContentDiv = Records.Where(rec => rec.DivName == "IncompleteReportsContentDiv").ElementAt(0).IsDivOpen;
                 if (IncompleteReportsContentDiv == true)
                 {
                     ViewBag.IncompleteReportsContent = "expand";
                 }
                 else
                 {
                     ViewBag.IncompleteReportsContent = "colapse";
                 }
                 bool DrugTestingOrdersContentDiv = Records.Where(rec => rec.DivName == "DrugTestingOrdersContentDiv").ElementAt(0).IsDivOpen;
                 if (DrugTestingOrdersContentDiv == true)
                 {
                     ViewBag.DrugTestingOrdersContent = "expand";
                 }
                 else
                 {
                     ViewBag.DrugTestingOrdersContent = "colapse";
                 }

             }

            
            AdminSearchModel ObjAdminSearchModel = new AdminSearchModel();
            if (TempData["NewAccounts"] != null)
            {
                if (TempData["message"] != null)
                {
                    ObjAdminSearchModel.strResultNewAccounts = TempData["message"].ToString();
                }
            }
            if (TempData["AdminConsent"] != null)
            {
                if (TempData["messages"] != null)
                {
                    ObjAdminSearchModel.strResultAdminConsent = TempData["messages"].ToString();
                }
            }
            ObjAdminSearchModel.DrugTestingReportType = 6;
            ObjAdminSearchModel.lnkDrugTesting = "Archive";

            ObjAdminSearchModel.HelpWithOrdersReportType = 1;
            ObjAdminSearchModel.lnkHelpWithOrders = "Archive";

            ObjAdminSearchModel.EmergeReviewReportType = 1;
            ObjAdminSearchModel.lnkEmergeReview = "Archive";

            ObjAdminSearchModel.AdminConsentReportType = 1;
            ObjAdminSearchModel.lnkAdminConsent = "Archive";

            ObjAdminSearchModel.CollTemplateContents = GetTemplateContentsById(Convert.ToInt32(EmailTemplates.ReportsNotGenerating), true);
            if (ObjAdminSearchModel.CollTemplateContents != null)
            {
             
                        ObjAdminSearchModel.SystemNotificationTitle = ObjAdminSearchModel.CollTemplateContents.ElementAt(0).TemplateSubject;
                        ObjAdminSearchModel.SystemNotificationContent = ObjAdminSearchModel.CollTemplateContents.ElementAt(0).TemplateContent;
                        ObjAdminSearchModel.SystemNotificationStatus = ObjAdminSearchModel.CollTemplateContents.ElementAt(0).IsEnabled;
                  

            }

            return View(ObjAdminSearchModel);
        }

        public ActionResult SaveSystemNotificationDetails(string Title, string Details)
        {
            string strSaveResult = string.Empty;

            BALEmailSystemTemplates ObjBALEmailSystemTemplates = new BALEmailSystemTemplates();
            try
            {
                int result = ObjBALEmailSystemTemplates.UpdateSystemNotification(Convert.ToInt32(EmailTemplates.ReportsNotGenerating), Title, Details, true);
                if (result == 1)
                {
                    strSaveResult = "<span class='successmsg'>Notification Updated Succesfully</span>";
                }
                else
                {
                    strSaveResult = "<span class='errormsg'>Error occurred while saving. Please try again!</span>";
                }
            }
            catch
            {
            }
            finally
            {
                ObjBALEmailSystemTemplates = null;
            }
            //List<Proc_USA_LoadEmailTemplatesResult> Obj = GetTemplateContentsById(Convert.ToInt32(EmailTemplates.ReportsNotGenerating), true);
            //if (Obj != null)
            //{
            // string TempCont = Obj.ElementAt(0).TemplateContent;

            //   string updatedContent = TempCont.Replace("%%NotificationSubject%%", Title).Replace("%%NotificationDetails%%", Details);
            //}

            return Json(new { Message = strSaveResult });
        }
        public ActionResult ClearSystemNotificationDetails()
        {
            string strSaveResult = string.Empty;

Source/Emerge/Controllers/Office/AdminAlertsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Emerge.Models;
using Emerge.Services;
using Emerge.Data;
using Emerge.Common;
using System.Web.Security;
using System.Text;

namespace Emerge.Controllers.Office
{
    public partial class OfficeController : Controller
    {
      
        //
        // GET: /AdminAlerts/

        public ActionResult AdminAlerts()
        {
            return View();
        }

        public ActionResult AlertsBinding(int page, int pageSize)
        {

        int PageNum = 1;
            int PageSize = 15;
            MembershipUser ObjMembershipUser = Membership.GetUser(Utility.GetUID(User.Identity.Name));

            Guid userId = new Guid(ObjMembershipUser.ProviderUserKey.ToString());
            BALOffice objBALOffice = new BALOffice();
            var alertsCollec = objBALOffice.GetAlertsForOfficeUser(userId,PageNum,PageSize,"CreatedDate","asc").ToList();
            return Json(new { Products = alertsCollec, TotalCount = alertsCollec.ElementAt(0).TotalRec},
                           JsonRequestBehavior.AllowGet);

        }



    }
}

Source/Emerge/Controllers/Office/AdminClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Emerge.Models;
using Emerge.Services;
using Emerge.Data;
using System.IO;
using System.Text.RegularExpressions;
using System.Net.Mail;
using System.Net.Mime;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using System.Security;
using System.Data.Linq;
using System.Web.Security;
using Emerge.Common;
using System.Text;

namespace Emerge.Controllers.Office
{
    public partial class OfficeController : Controller
    {
       // Page Load Method 
        public ActionResult AdminClients()
        {
            return View();
        }
        // Grid Bind Method
        public ActionResult GetAdminClients(int page, int pageSize, List<GridSort> sort, List<GridFilter> filters)
        {
            try
            {
                Guid UserId = Utility.GetUID(User.Identity.Name);
                BALLeads ObjBALLeads = new BALLeads();
                var Managerid = Guid.Empty;
                Guid saleid = Guid.Empty;
                string Searchkeyword = "";
                var Status = "SelectStatus";
                string Direction = "Desc";
                string ColumnName = "CreatedDate";
                string ToDate = "";
                string FromDate = "";
              string filterColumn=string.Empty;
              byte FilterAction = 2; 
                string filterValue=string.Empty;
                if (sort != null)
                {
                Direction = sort[0].Dir;
                ColumnName = sort[0].Field;
                }
               // ClientsModel objClientmodel = new ClientsModel();
                if (filters != null)
                {
                        FilterAction = 1;
                        filterColumn = filters[0].Field;
                        filterValue = filters[0].Value;
                    
                }

                var list = ObjBALLeads.GetAllClients(page, pageSize, true, Searchkeyword, -1, Status, ColumnName, Direction, FromDate, ToDate, Managerid, saleid, UserId, "", filterColumn, FilterAction, filterValue);
                if (list.Count > 0)
                {
                    return Json(new { Reclist = list, TotalRec = list.ElementAt(0).TotalRec });
                }
                else
                {
                    return Json(new { Reclist = 0, TotalRec = 0});
 
                }
            }
            catch {
                return Json(new { Reclist = 0, TotalRec = 0 });
            }
        }

    }
}

Source/Emerge/Controllers/Office/AdminLeadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Emerge.Data;
using Emerge.Services;
using Emerge.Models;
using System.Web.Security;
using Emerge.Common;

namespace Emerge.Controllers.Office
{
    public partial class OfficeController : Controller
    {
       
        //Page Load Method 
        public ActionResult AdminLeads()
        {
            return View();
        }
        // Grid Bind Method
        public ActionResult GetAllAdminLeads(int page, int pageSize, List<GridSort> sort, List<GridFilter> filters)
        {


            BALLeads ObjBALLeads = new BALLeads();
            Guid UserId = Utility.GetUID(User.Identity.Name);
            byte LeadType = 0;
            var Managerid = Guid.Empty;
            Guid saleid = Guid.Empty;
            string Searchkeyword = "";
            string copanytype = "-1";
            string Direction = "Desc";
            string ColumnName = "CreatedDate";
            if (sort != null)
            {
                Direction = sort[0].Dir;
                ColumnName = sort[0].Field;
            }
            byte LeadStatus = 0;
            string LeadSource = string.Empty;
           
            string ToDate = "";
            string FromDate = "";
            byte FilterAction = 2; // Set FilterAction =1 if filter from coloumn from
            string FilterColumn = string.Empty;
            string FilterValue = string.Empty;

            string LeadNextStep = string.Empty;
            string SalesAssosiate = string.Empty;

            if (filters != null)
            {
               
                    FilterAction = 1;
                    FilterColumn = filters[0].Field;
                    FilterValue = filters[0].Value;
                
            }

            var ObjDbCollection = ObjBALLeads.GetAllLeads(page, pageSize, true, Searchkeyword, short.Parse(copanytype), -1, ColumnName, Direction, FromDate, ToDate, LeadStatus, Managerid, saleid, UserId, LeadSource, LeadType, FilterColumn, FilterAction, FilterValue,LeadNextStep, SalesAssosiate);
            if (ObjDbCollection.Count > 0)
            {
                return Json(new { Products = ObjDbCollection, TotalCount = ObjDbCollection.ElementAt(0).TotalRec });
            }
            else
            {
                return Json(new { Products = ObjDbCollection, TotalCount = 0 });
            }

        }

    }
}

Source/Emerge/Controllers/Office/AdminSalesReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Emerge.Controllers.Office
{
    public partial class OfficeController : Controller
    {
        //
        // GET: /AdminSalesReports/

        public ActionResult AdminSalesReports()
        {       
   
            return View();
        }

    }
}

Source/Emerge/Controllers/Office/AlertsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Emerge.Services;
using Emerge.Common;
using Emerge.Models;
using Emerge.Data;
using System.Web.Security;
using System.IO;
using System.Web.UI.WebControls;
using System.Net.Mail;
using System.Text;

namespace Emerge.Controllers.Office
{
    public partial class OfficeController : Controller
    {
        // Page Load Method
        public ActionResult Alerts()
        {

            return View();
        }

        // Grid Bind Method
        public ActionResult GetAllAlerts(int page, int pageSize)
        {
             MembershipUser ObjMembershipUser = Membership.GetUser(Utility.GetUID(User.Identity.Name));
            Guid Userid=  new Guid(ObjMembershipUser.ProviderUserKey.ToString());
            BALOffice  objbalOffice= new BALOffice();
            var list = objbalOffice.GetAlertsForOfficeUser(Userid, page, pageSize, "CreatedDate", "DESC").ToList();

            return Json(new { Products = list});
        }

    }
}

Source/Emerge/Views/Office/AdminSearch.cshtml
@{
    ViewBag.Title = "Admin Search";
    Layout = "~/Views/Shared/_OfficeLayout.cshtml";
}
<style>
.plus_btn
        {
            background-image: url('../../content/themes/base/images/plus_symbol.png');
            background-repeat: no-repeat;
             background-position:right;
               width:50px !important;
             height:34px; 
        }
        
         .expand
    {
        }
        .colapse
        {
            }
</style>
<script src="@Url.Content("~/Scripts/EmergeCompressedJavascript.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-1.7.1.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/KendoJS/kendo.web.js")" type="text/javascript"></script>

<div id="content-box">
    <div class="padding">
        <div class="clr">
        </div>
        <div id="element-box" style="margin-top: 10px; padding-top: 1px; margin-bottom: 1px;">
            <div class="t">
                <div class="t">
                    <div class="t">
                    </div>
                </div>
            </div>
            <div class="m">
                <div class="header1" style="padding: 0px 0px 0px 0px; margin-bottom: 1px; width: 60%">
                   <input type="hidden" value="2" id="flag2" />
                </div>
               @*  <div class="plus_btn" width="39px" height="34px" onclick="ExpandAndCollapse()"  ></div>*@
                 <input type="hidden" id="hdnCompleteDemo" value="@ViewBag.DemomContensofficeDiv"  />
                 <div class="header1" style="padding: 0px 0px 0px 0px; margin-bottom: 1px; width: 60%" onclick="ExpandAndCollapse()">Demos</div>
                <div id="DemomContensofficeDiv"  class="expand">
                
                @Html.Partial("PartialCompleteDemo")
                   @Html.Partial("PartialCalendar")</div>
                <div class="clr">
                </div>
            </div>
            <div class="b">
                <div class="b">
                    <div class="b">
                    </div>
                </div>
            </div>
        </div>
        <div class="clr">
        </div>
        <div id="element-box" style="margin-top: 10px; padding-top: 2px;">
            <div class="t">
                <div class="t">
                    <div class="t">
                    </div>
                </div>
            </div>
            <div class="m">
               
               @* <div class="plus_btn" width="39px" height="34px" onclick="ExpandAndCollapseQuality()"  ></div>*@
                 <div class="header1" style="padding: 0px 0px 0px 0px; width: 60%" onclick="ExpandAndCollapseQuality()" >
                    Quality Control Survey <input type="hidden" id="hdnQualityContentoffice" value="@ViewBag.QualityContentsofficeDiv" />
                </div>
                <div id="QualityContentsofficeDiv" class="expand">
                
                @Html.Partial("PartialQualityControlOffice")</div>
                <div class="clr">
                </div>
            </div>
            <div class="b">
                <div class="b">
                    <div class="b">
                    </div>
                </div>
            </div>
        </div>
        <div class="clr">
        </div>
        <div class="clr">
        </div>
    </div>
</div>
<script>
    
    function ExpandAndCollapse() {


        var flag = document.getElementById("DemomContensofficeDiv").className;
        var SectionId = "DemomContensofficeDiv";

        if (flag == "expand") {
            $.post('@Url.Action("SaveColapseStatus", "Control")', { SectionId: SectionId, Status: "true" }, function (NotificationResult) {
                $("#DemomContensofficeDiv").slideDown(200, "linear", "SaveSlideChages");
                $("#DemomContensofficeDiv").addClass("colapse").removeClass("expand");
            });


        }
        else if (flag == "colapse") {
            $.post('@Url.Action("SaveColapseStatus", "Control")', { SectionId: SectionId, Status: "false" }, function (NotificationResult) {
                $("#DemomContensofficeDiv").slideUp(200, "linear", "SaveSlideChages");
                $("#DemomContensofficeDiv").addClass("expand").removeClass("colapse");
            });

        }
        
    }


    function onpageload() {
        var flag = document.getElementById("hdnQualityContentoffice").value;

        if (flag == "expand") {
            $("#QualityContentofficeDiv").slideDown(200, "linear", "SaveSlideChages");
            $("#QualityContentofficeDiv").addClass("colapse").removeClass("expand");

        }
        else if (flag == "colapse") {

            $("#QualityContentofficeDiv").slideUp(200, "linear", "SaveSlideChages");
            $("#QualityContentofficeDiv").addClass("expand").removeClass("colapse");

        }

        var hdnCompleteDemo = document.getElementById("hdnCompleteDemo").value;
        //alert(hdnCompleteDemo);
        if (hdnCompleteDemo == "expand") {
            $("#DemomContensofficeDiv").slideDown(200, "linear", "SaveSlideChages");
            $("#DemomContensofficeDiv").addClass("colapse").removeClass("expand");

        }
        else if (hdnCompleteDemo == "colapse") {
        
            $("#DemomContensofficeDiv").slideUp(200, "linear", "SaveSlideChages");
            $("#DemomContensofficeDiv").addClass("expand").removeClass("colapse");

        }
    }
    onpageload();

   
    function ExpandAndCollapseQuality() {
        var flag = document.getElementById("QualityContentsofficeDiv").className;
        var SectionId = "QualityContentsofficeDiv";

        if (flag == "expand") {
            $.post('@Url.Action("SaveColapseStatus", "Control")', { SectionId: SectionId, Status: "true" }, function (NotificationResult) {
                $("#QualityContentsofficeDiv").slideDown(200, "linear", "SaveSlideChages");
                $("#QualityContentsofficeDiv").addClass("colapse").removeClass("expand");
            });


        }
        else if (flag == "colapse") {
            $.post('@Url.Action("SaveColapseStatus", "Control")', { SectionId: SectionId, Status: "false" }, function (NotificationResult) {
                $("#QualityContentsofficeDiv").slideUp(200, "linear", "SaveSlideChages");
                $("#QualityContentsofficeDiv").addClass("expand").removeClass("colapse");
            });

        }
    }

</script>

Source/Emerge/Views/Office/PartialRunJuno.cshtml
<style>
.milestone_badlead
{
    background-color: #000000;
    border-width: 0;
    color: #FFFFFF;
    padding: 0 2px;
    text-align: center;
    }
    .milestone_notinterest
{
    background-color: #d62f37;
    border-width: 0;
    color: #FFFFFF;
    padding: 0 2px;
    text-align: center;
    }
    .milestone_callback
{
    background-color: #e5b228;
    border-width: 0;
    color: #FFFFFF;
    padding: 0 2px;
    text-align: center;
    }
    .milestone_addnew
{
    background-color:#059a02;
    border-width: 0;
    color: #FFFFFF;
    padding: 0 2px;
    text-align: center;
    }

</style>


<div style="display: block; visibility: hidden;max-height:532px;" id="RunJunowindow">
    <table border="0" style="width: 100%">
        <tr>
            <td align="center">
              <div id="leadmsgbox" style="display: none">

</div>
            </td>
        </tr>
        <tr>
            <td align="center">
                <div id="RunJunogridUnique">
                </div>
            </td>
        </tr>
    </table>
</div>
<script type="text/javascript">

    function RunJuno() {
        $.ajax('@Url.Action("PartialRunJunoUnique", "Office")', { cache: false, success: function (data) {
            $("#RunJunogridUnique").html(data);
            $("#leadmsgbox").hide();

            document.getElementById("RunJunowindow").style.visibility = "visible";
            var windowOpen = $("#RunJunowindow").kendoWindow({
                actions: ["Close"],
                draggable: true,
                scrollable: false,
                modal: true,
                resizable: true,
                title: "Juno",
                width: "1370px"

            }).data("kendoWindow");
            windowOpen.center();
            windowOpen.open();
         } });
   
    }
    
  


</script>

Source/Emerge/Views/Office/Users.cshtml
@{
    ViewBag.Title = "Users";
    Layout = "~/Views/Shared/_OfficeLayout.cshtml";
}

<h2>Users</h2>