Source/Emerge/Controllers/Common/CommonAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web.Http;
using Emerge.Services;

namespace Emerge.Controllers.Common
{
    public class CommonAPIController : ApiController
    {
        public string GetAllReports(string id)
        {
            string ReportName = string.Empty;
            try
            {
                string[] arr = id.Split('_');
                BALGeneral ObjGeneral = new BALGeneral();
                ReportName = ObjGeneral.GetEmergeProductPackageReportsNew(Convert.ToInt32(arr[0]), Convert.ToInt32(arr[1]));
            }
            catch (Exception)
            {
            }
            return ReportName;
        }
    }
}

Source/Emerge/Controllers/Common/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Emerge.Services;
using Emerge.Common;
using System.Web.Security;
using Emerge.Models;
using System.Configuration;
using Emerge.Data;
using System.Text;
using System.Text.RegularExpressions;
using System.IO;
using System.Web.UI;
using System.Net.Mail;
using iTextSharp.text;
using iTextSharp.text.pdf;
//using RazorEngine;

namespace Emerge.Controllers.Common
{
    public class CommonController : Controller
    {
        BALManageFolder objBALManageFolder = new BALManageFolder();
        BALBillingData ObjBALBillingData = new BALBillingData();
        Guid SiteApplicationId = Emerge.Common.Utility.SiteApplicationId;// new Guid("65d1e085-eb17-4f29-96d0-247b0c1ee852");

        public PartialViewResult PartialDropDownsData(string PType)
        {
            //int CompanyId = 0;
            //int LocationId = 0;
            string RoleName = "SystemAdmin";
            ViewData["listMonth"] = FillMonth();
            ViewData["listYear"] = FillYear();

            #region Company List
            List<SelectListItem> listCompany = new List<SelectListItem>();
            var companies = ObjBALBillingData.GetAllCompany(SiteApplicationId, true, false);
            if (companies.Count() > 0)
            {
                //listCompany = companies.Select(x => new SelectListItem { Text = x.CompanyName, Value = x.pkCompanyId.ToString() }).ToList();
                //CompanyId = companies.ElementAt(0).pkCompanyId;
                ViewData["CompanyId"] = companies.ElementAt(0).pkCompanyId;
            }
            ViewData["PType"] = "";
            if (!string.IsNullOrEmpty(PType))
            {
                ViewData["PType"] = PType;
                listCompany.Insert(0, new SelectListItem { Text = "---All Companies---", Value = "" });
            }
            if (Session["fkcmpId1"] != null)
            {
                ViewData["CompanyId"] = Session["fkcmpId1"].ToString();
                Session["pkCompanyId"] = Session["fkcmpId1"].ToString();
            }
            #endregion

            #region Locations List
            //List<SelectListItem> listLocations = new List<SelectListItem>();
            //var Locations = ObjBALBillingData.GetLocationsByCompanyId(CompanyId, SiteApplicationId);
            //if (Locations.Count() > 0)
            //{
            //    listLocations = Locations.Select(x => new SelectListItem { Text = x.DisplayLocation, Value = x.LocationId.ToString() }).ToList();
            //    LocationId = Locations.ElementAt(0).LocationId;
            //}
            //listLocations.Insert(0, new SelectListItem { Text = "---All Locations---", Value = "" });
            #endregion

            #region Users List
            //List<SelectListItem> listUsers = new List<SelectListItem>();
            //var Users = ObjBALBillingData.GetCompanyUsersByLocationId(CompanyId, LocationId, SiteApplicationId);
            //if (Users.Count() > 0)
            //{
            //    listUsers = Users.Select(x => new SelectListItem { Text = x.UserEmail, Value = x.CompanyUserId.ToString() }).ToList();
            //}
            //listUsers.Insert(0, new SelectListItem { Text = "---All Users---", Value = "" });
            #endregion

            #region ReferenceCode List
            //List<SelectListItem> listReferenceCode = new List<SelectListItem>();
            //var ReferenceCode = ObjBALBillingData.GetAllReferenceCodes(CompanyId);
            //if (ReferenceCode.Count() > 0)
            //{
            //    listReferenceCode = ReferenceCode.Select(x => new SelectListItem { Text = x.ReferenceCode, Value = x.pkReferenceCodeId.ToString() }).ToList();
            //}
            //listReferenceCode.Insert(0, new SelectListItem { Text = "---All Reference---", Value = "" });
            #endregion

            #region salesRep List
            RoleName = "salesmanager";//salesrep
            List<SelectListItem> listsalesRep = new List<SelectListItem>();
            var salesRep = ObjBALBillingData.GetSalesRep(RoleName);
            if (salesRep.Count() > 0)
            {
                listsalesRep = salesRep.Select(x => new SelectListItem { Text = x.FullName, Value = x.pkSalesRepId.ToString() }).ToList();
            }
            listsalesRep.Insert(0, new SelectListItem { Text = "---Select Sales Rep---", Value = "" });
            #endregion
            List<SelectListItem> listUser = new List<SelectListItem>();

            //listsalesRep = salesRep.Select(x => new SelectListItem { Text = x.FullName, Value = x.pkSalesRepId.ToString() }).ToList();
            listUser.Insert(0, new SelectListItem { Text = "---All Users---", Value = "-1" });

            ViewBag.stateList = listUser;
            //ViewData["listCompany"] = listCompany;
            //ViewData["listLocation"] = listLocations;
            //ViewData["listUsers"] = listUsers;
            ViewData["listSalesRep"] = listsalesRep;
            //ViewData["listReferenceNo"] = listReferenceCode;
            return PartialView("../Common/PartialDropDownsData");
        }

        public PartialViewResult PartialVendorDeopdownsData()
        {
            int VendorId = 0;
            ViewData["listMonth"] = FillMonth();
            ViewData["listYear"] = FillYear();

            #region Vendors List
            List<SelectListItem> listVendors = new List<SelectListItem>();
            var Vendors = ObjBALBillingData.GetVendorDetails();
            if (Vendors.Count() > 0)
            {
                listVendors = Vendors.Select(x => new SelectListItem { Text = x.VendorName, Value = x.pkVendorId.ToString() }).ToList();
            }
            listVendors.Insert(0, new SelectListItem { Text = "---All Vendors---", Value = "" });
            #endregion

            #region Report Type List
            List<SelectListItem> listReportType = new List<SelectListItem>();
            var ReportTypes = ObjBALBillingData.GetReportsByVendorId(VendorId);
            if (ReportTypes.Count() > 0)
            {
                listReportType = ReportTypes.Select(x => new SelectListItem { Text = x.ReportName, Value = x.pkReportId.ToString() }).ToList();
            }
            listReportType.Insert(0, new SelectListItem { Text = "---Reports---", Value = "" });
            #endregion


            ViewData["listVendors"] = listVendors;
            ViewData["listReportType"] = listReportType;

            return PartialView("../Common/PartialDropDownsForVendorReport");
        }
        public PartialViewResult PartialSalesDropDownsData()
        {
            int CompanyId = 0;
            //int LocationId = 0;
            //string RoleName = "SystemAdmin";
            ViewData["listMonth"] = FillMonth();
            ViewData["listYear"] = FillYear();
            ViewData["listAccountStatus"] = GetAccountStatusList();

            #region Company List
           // List<SelectListItem> listCompany = new List<SelectListItem>();
            var companies = ObjBALBillingData.GetAllCompany(SiteApplicationId, true, false);
            if (companies.Count() > 0)
            {
                //listCompany = companies.Select(x => new SelectListItem { Text = x.CompanyName, Value = x.pkCompanyId.ToString() }).ToList();
                //CompanyId = companies.ElementAt(0).pkCompanyId;
                ViewData["CompanyId"] = companies.ElementAt(0).pkCompanyId;
            }
            //listCompany.Insert(0, new SelectListItem { Text = "---All Companies---", Value = "" });
            #endregion

            #region Locations List
            //List<SelectListItem> listLocations = new List<SelectListItem>();
            //var Locations = ObjBALBillingData.GetLocationsByCompanyId(CompanyId, SiteApplicationId);
            //if (Locations.Count() > 0)
            //{
            //    listLocations = Locations.Select(x => new SelectListItem { Text = x.DisplayLocation, Value = x.LocationId.ToString() }).ToList();
            //    LocationId = Locations.ElementAt(0).LocationId;
            //}
            //listLocations.Insert(0, new SelectListItem { Text = "---All Locations---", Value = "" });
            #endregion

            #region Users List
            //List<SelectListItem> listUsers = new List<SelectListItem>();
            //var Users = ObjBALBillingData.GetCompanyUsersByLocationId(CompanyId, LocationId, SiteApplicationId);
            //if (Users.Count() > 0)
            //{
            //    listUsers = Users.Select(x => new SelectListItem { Text = x.UserEmail, Value = x.CompanyUserId.ToString() }).ToList();
            //}
            //listUsers.Insert(0, new SelectListItem { Text = "---All Users---", Value = "" });
            #endregion

            #region ReferenceCode List
            List<SelectListItem> listReferenceCode = new List<SelectListItem>();
            var ReferenceCode = ObjBALBillingData.GetAllReferenceCodes(CompanyId);
            if (ReferenceCode.Count() > 0)
            {
                listReferenceCode = ReferenceCode.Select(x => new SelectListItem { Text = x.ReferenceCode, Value = x.pkReferenceCodeId.ToString() }).ToList();
            }
            listReferenceCode.Insert(0, new SelectListItem { Text = "---All Reference---", Value = "" });
            #endregion

            #region salesRep List
            List<SelectListItem> listAccManager = new List<SelectListItem>();
            BALSalesRep ObjBALSalesRep = new BALSalesRep();
            string Role_Name = "salesmanager";//salesrep
            var accManager = ObjBALSalesRep.GetSalesManagers(Role_Name);
            if (accManager.Count() > 0)
            {
                listAccManager = accManager.Select(x => new SelectListItem { Text = x.FullName, Value = x.fkUserId.ToString() }).ToList();
            }
            listAccManager.Insert(0, new SelectListItem { Text = "---Select Account Manager---", Value = "" });
            #endregion

Source/Emerge/Controllers/Common/CommonJunoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Emerge.Services;
using Emerge.Models;
using System.Web.Security;

namespace Emerge.Controllers.Common
{
    public class CommonJunoController : Controller
    {
        //
        // GET: /CommonJuno/

        public PartialViewResult Index(string LeadStatus)
        {
            ViewBag.LeadStatus = LeadStatus;
            return PartialView("../Common/PartialJuno");
        }

        [HttpPost]
        public ActionResult GetNewJunos(int page, int pageSize, string group, List<GridSort> sort, List<GridFilter> filters)
        {
            BALJuno ObjBALJuno = new BALJuno();
           
            
            #region Sorting
            int iTotalRecords = 0;
            int iPageNo = page;
            int PageSize = pageSize;
            string ColumnName = "CreatedDate";
            string Direction = "DESC";
            if (sort != null)
            {
                Direction = sort[0].Dir;
                ColumnName = sort[0].Field;
            }

            #endregion

            #region Filtering
            byte LeadStatus = 0;
            if (filters != null)
            {
                LeadStatus = !string.IsNullOrEmpty(filters[0].Value) ? byte.Parse(filters[0].Value) : byte.Parse("0");
            }
            #endregion

            var ObjDbCollection = ObjBALJuno.GetNewJunos(ColumnName, Direction, true, iPageNo, PageSize, LeadStatus);

            if (ObjDbCollection.Count > 0)
            {
                iTotalRecords = int.Parse(ObjDbCollection.ElementAt(0).TotalRec.ToString());
            }
            // return Json(ObjDbCollection);
            return Json(new { Products = ObjDbCollection, TotalCount = iTotalRecords });
        }

    }
}

Source/Emerge/Views/Common/PartialCurrentFeaturenew.cshtml
@model Emerge.Models.LoginModel
@using Emerge.Common;
<table cellpadding="0" cellspacing="0" style="margin: 0 auto;">
    <tr>
        <td>
            <center>
                <div>
                   @{string UploadedTitleImage = @Model.TitleImage;}
                    @if (Model.TitleImage != " " && Model.TitleImage != "" && Model.TitleImage != null){ <div id="lblFeatureTitleImage" style="padding-top: 10px; font-size: 14px;"> <img  src="@Model.TitleImage"/></div>  }
                    else{  <span style="font-size: 25px; color: #706e70;">@Model.Title</span> }
                </div>
            </center>
        </td>
    </tr>
    <tr>
        <td>
            <center>
                @{string UploadedFile = @Model.UploadedFile;}
                @{string Ext = UploadedFile.Split('.')[1];}
                @if (Ext == "flv" || Ext == "swf")
                {  <div class="videopopup" style="height: 290px; width: 435px; margin:6% auto 0;" onmousedown="enlargeVidImgG(@Model.FeatureId)" >
                    <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="100%" height="100%">
                        <param name="movie" value="@Url.Content("~/Resources/Upload/FeatureFiles/" + Model.UploadedFile + "")" />
                        <param name="quality" value="high" />
                        <param name="play" value="false" />
                        <param name="loop" value="false" />
                        <embed src="@Url.Content("~/Resources/Upload/FeatureFiles/" + Model.UploadedFile + "")" width="100%" height="100%" play="false" loop="false" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash"></embed>
                    </object>
                </div>
                }
                else
                {  <div style="margin-top: 10%;">
                    <img id="ImgFile" src="@Model.UploadedFile" alt="" onclick="enlargeVidImgG(@Model.FeatureId)" />
                  </div>
                }
            </center>
        </td>
    </tr>
    <tr>
        <td>
            <center>
                <div style="padding-top: 15px; font-size: 18px; color: #706e70; margin-top: 7%;">
                    <p align="center">@Model.Description</p>
                </div>
            </center>
        </td>
    </tr>
    <tr>
        <td>
            @if (Model.IsPrevious == false)
            { <img alt="" style="display: none;" src="@Url.Content("~/Content/themes/base/Images/prev_btnnew_off.png")"  /> <input type="hidden" value="@Model.IsPrevious" id="IsPrevious"/> }
            else
            { <img alt=""  style="display:none;" class="previous" src="@Url.Content("~/Content/themes/base/Images/prev_btnnew_on.png")" onclick="previous(@Model.CurrentFeature-1)" /> <input type="hidden" value="@Model.IsPrevious" id="IsPrevious"/> }
            &nbsp;
            @if (Model.IsNext == false)
            { <img alt="" style="display: none;" id="closefeature" src="@Url.Content("~/Content/themes/base/Images/next_btnnew_off.png")" onclick="CloseFeature();" /> <input type="hidden" value="@Model.IsNext" id="isnext"/> }
            else
            { <img alt="" style="display:none;"  class="next" src="@Url.Content("~/Content/themes/base/Images/next_btnnew_on.png")" onclick="next(@Model.CurrentFeature)" /> <input type="hidden" value="@Model.IsNext" id="isnext"/> }
        </td>
    </tr>
</table>
<div style="display: none;" id="div5">
</div>
<script type="text/javascript">
    $(function () { if ($("#poppro").val() != "1") { $("#ImgFile").click(); } });
    $("#div5").toggle(function () {
    $("#anotherDiv").hide("slide", { direction: 'right' }, 3000);
    $("#oneDiv").show("slide", { direction: 'left' }, 3000);
    }, function () {
    $("#anotherDiv").show("slide", { direction: 'right' }, 3000);
    hide("slide", { direction: 'left' }, 3000);
    }).css({ position: 'absolute' });
    function CloseFeature() { $.post('@Url.Action("UpdateViewCount", "Common")', {}, function (Result) { $("#closefeature").closest(".k-window-content").data("kendoWindow").close(); }); }
    function enlargeVidImgG(FeatureId) {
    var body = document.getElementsByTagName('body')[0];
    if (jQuery.browser.msie) {
    document.body.style.overflowX = "hidden";
    document.body.style.overflowY = "hidden";
    $("#DivNewFeature").css({ position: 'absolute' });}
    if (FeatureId != "") {
    $.post('@Url.Action("LoadFeaturePreviewForEnlarge", "Common")', { FeatureId: FeatureId }, function (ObjtblFeature) {
    $("#divEnlarge").kendoWindow();
    var UploadedFile = ObjtblFeature.UploadedFile;
    var Ext = UploadedFile.split('.')[1];
    var FilePath = "./Resources/Upload/FeatureFiles/" + ObjtblFeature.UploadedFile;
    var divImgFile = $("#VidImgFile");
    if (Ext == "flv" || Ext == "swf") {
    var ObjectFile = "<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" width=\"100%\" height=\"100%\">";
    var Params = "<param name=\"movie\" value=\'" + FilePath + "\' /><param name=\"quality\" value=\"high\" /><param name=\"play\" value=\"false\" />";
    var Params1 = "<param name=\"loop\" value=\"false\" />";
    var src = "<embed src=\'" + FilePath + "\' width=\"100%\" height=\"100%\" play=\"false\" loop=\"false\" quality=\"high\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" type=\"application/x-shockwave-flash\"></embed></object>";
    divImgFile.html(ObjectFile + Params + Params1 + src); }
    else { divImgFile.html('<img src="' + ObjtblFeature.UploadedFile + '"/>'); }
    $("#divEnlarge").attr('style', "width: 920px;height:690px; display:block;");
    var kendoWindow = $("#divEnlarge").data("kendoWindow");
    var windowTitle = kendoWindow.title("Preview");
    $("#divEnlarge").data("kendoWindow").center();
    $("#divEnlarge").data("kendoWindow").open();
    if ($("#poppro").val() != "1") { $("#divEnlarge").data("kendoWindow").close();
    $("#poppro").val("1") }}); } }
    function previous(val) {
    $("#poppro").val("1");
    if (val != "0") { val = val - 1; }
    if (jQuery.browser.msie) { $("#DivNewFeature").css({ position: 'absolute' }); }
    else { $("#DivNewFeature").css({ position: 'absolute' }); }
    $.ajax({ cache: false, type: "POST", url: '@Url.Action("LoadFeaturenew", "Common")', data: { CurrentFeature: val, IsNext: false }, success: function (data) {
    $("#feature").html(data);
    $("#checklist").html($("#DivNewFeature").html());}});
    $("#DivNewFeature").hide("slide", { direction: 'right' }, 1000);
    $("#checklist").show("slide", { direction: 'left' }, 1000, function () {
    $("#DivNewFeature").show();
    $("#checklist").html('');});}
    function next(val) {
    $("#poppro").val("1");$("#checklist").removeAttr('style');
    $("#checklist").attr('style', 'display: block; width: 100%; height: 620px;background-color: white;');
    if (jQuery.browser.msie) { $("#DivNewFeature").css({ position: 'absolute' }); }
    else { $("#DivNewFeature").css({ position: 'absolute' }); }
    $.ajax({ cache: false, type: "POST", url: '@Url.Action("LoadFeaturenew", "Common")', data: { CurrentFeature: val, IsNext: true }, success: function (data) {
    $("#feature").html(data); $("#checklist").html($("#DivNewFeature").html()); }});
    $("#DivNewFeature").hide("slide", { direction: 'left' }, 1000);
    $("#checklist").show("slide", { direction: 'right' }, 1000, function () {
    $("#DivNewFeature").show(); $("#checklist").html(''); }); }
    function nextimage() { $("#poppro").val("1"); if ($("#isnext").val() == "value") { $("img[class=next]").click(); }
    else { location.href = "Default/RedirectToPage?Email=" + $("#UserName").val() + "&Page=" + $("#tempresult").val(); } }
    function previousimage() { $("#poppro").val("1"); if ($("#IsPrevious").val() == "value") { $("img[class=previous]").click(); } }
    </script>

Source/Emerge/Views/Common/PartialEmergeEdit.cshtml
<div style="border-color: Black; border-width: 0px; border-style: solid; overflow-x: hidden;
    display: block; visibility: visible;" id="EmergeEditwindow">
    <table width="100%" border="0" style="height: 320px; display: block;" id="Table3">
        <tbody>
            <tr>
                <td align="left" style="height: 2px; display: none;">
                    <b><span class="text"><span id="lblEMHeader">
                        </span></span></b>
                </td>
            </tr>
            <tr>
                <td>
                    <table width="100%" cellpadding="2">
                        <tbody>
                            <tr>
                                <td align="left" colspan="2">
                                    Make a suggestion on how to improve this section of Emerge.
                                </td>
                            </tr>
                            <tr>
                                <td align="left">
                                    From:
                                </td>
                                <td align="left">
                                    <span id="lblFrom"></span>
                                </td>
                            </tr>
                            <tr>
                                <td align="left">
                                    To:
                                </td>
                                <td>
                                    <span id="lblTo"></span>
                                </td>
                            </tr>
                            <tr>
                                <td align="left">
                                    Subject:
                                </td>
                                <td>
                                    <span id="lblEMSubject"></span>
                                </td>
                            </tr>
                            <tr>
                                <td align="left" valign="top">
                                    Suggestions:
                                </td>
                                <td>
                                    &nbsp;
                                </td>
                            </tr>
                            <tr>
                                <td align="left" valign="top">
                                    &nbsp;
                                </td>
                                <td>
                                    <textarea style="height: 100px; width: 240px;" id="txtSuggestions" cols="20" rows="2"
                                        name="txtSuggestions"></textarea>&nbsp;
                                </td>
                            </tr>
                            <tr>
                                <td align="left" valign="top" colspan="2" height="25px">
                                    <div style="margin-left: 80px">
                                        <span style="color: Red; display: none;" id="spnReqSugg">Please input
                                            your suggestions</span>
                                        <input type="hidden" id="EmailContent" />
                                        <input type="hidden" id="Company" />
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                </td>
                                <td align="right">
                                        <img  id="btnSuggestions" onclick="return SendEmail();" src="@Url.Content("~/Content/themes/base/images/email-send-icon.png")" alt="Send" title="Send" style="cursor:pointer" />
                                        <img id="imgSugLoader" src="@Url.Content("~/Content/themes/base/images/beginsearchbtn_clicked.gif")" alt="loader" style="display: none;" />
                                    @*<input type="submit" id="btnSendEMEditMail" value="Send" onclick="return SendEmail();" />*@
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
    <table width="100%" height="260px" style="display: none; font-size: 14px; vertical-align: top"
        id="EMEditMsgTable">
        <tbody>
            <tr bgcolor="#cccccc">
                <td align="left" width="365px" height="26px">
                    Message :
                </td>
            </tr>
            <tr>
                <td height="50px">
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td align="center" valign="middle">
                    <span style="display: inline-block; " id="lblEMEditMsg"></span>
                </td>
            </tr>
            <tr>
                <td>
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td align="center">
                    <input type="button" id="btnOk" onclick="CloseEMPopUp();"  value="OK" />
                </td>
            </tr>
        </tbody>
    </table>
</div>
<script type="text/javascript">
    function GetEmergeEditEmailTemplate(Header) {
        $.post('@Url.Action("GetEmergeEditEmailTemplate", "Common")', function (result) {
            clearMessage();
            $("#lblEMHeader").html(Header);
            $("#lblFrom").html(result.From);
            $("#lblTo").html(result.To);
            $("#lblEMSubject").html(Header);
            $("#Company").val(result.Cmp);
            $("#EmailContent").val(result.EContent);
            document.getElementById("EmergeEditwindow").style.visibility = "visible";
            var windowOpen = $("#EmergeEditwindow").kendoWindow({
                actions: ["Close"],
                draggable: true,
                height: "350px",
                modal: true,
                resizable: true,
                title: Header,
                width: "410px"
            }).data("kendoWindow");
            windowOpen.center();
            windowOpen.open();
            $("#imgSugLoader").css("display", "none");
            $("#btnSuggestions").css("display", "block");
            $(".k-widget").css("zoom", "1");
        });
    }

    function SendEmail() {
        var spnReqSugg = document.getElementById("spnReqSugg");
        var txtSuggestions = document.getElementById("txtSuggestions").value;
        if (txtSuggestions != '') {
            document.getElementById("imgSugLoader").style.display = 'block';
            document.getElementById("btnSuggestions").style.display = 'none';
            $.post('@Url.Action("SendEmail", "Common")', { Company: $("#Company").val(), MailFrom: $("#lblFrom").html(), Subject: $("#lblEMSubject").html(), EContent: $("#EmailContent").val(), Suggestion: $("#txtSuggestions").val() }, function (result) {

                $("#Table3").css('display', 'none');
                $("#EMEditMsgTable").css('display', 'block');
                $("#lblEMEditMsg").html(result.Msg);
                $("#lblEMEditMsg").addClass(result.Css);
            });
            spnReqSugg.style.display = "none";
            return true;
        }
        else {
            spnReqSugg.style.display = "block";
            return false;
        }
    }

    function CloseEMPopUp() {
        // alert("");
        //$("#EMEditMsgTable").hide();
        //$("#DivEM").hide();
        $("#EmergeEditwindow").data("kendoWindow").close();
        clearMessage();
        return false;
    }

    function clearMessage() {
        $("#Table3").css('display', 'block');
        $("#EMEditMsgTable").css('display', 'none');
        $("#spnReqSugg").css('display', 'none');
        $("#lblEMHeader").html('');
        $("#lblFrom").html('');
        $("#lblTo").html('');
        $("#lblEMSubject").html('');
        $("#Company").val('');
        $("#EmailContent").val('');
        $("#txtSuggestions").val('');
        $("#lblEMEditMsg").html('');
        $("#lblEMEditMsg").removeClass("successmsg");
        $("#lblEMEditMsg").removeClass("errormsg");
    }
</script>

Source/Emerge/Views/Common/PartialSalesReports.cshtml
<div id="clr_start" class="clr">
</div>
<div id="element-box">
    <div class="t">
        <div class="t">
            <div class="t">
            </div>
        </div>
    </div>
    <div class="m">
        <div id="divbillpdf">
            <div id="PartialContent">
                @Html.Partial("../Common/PartialSalesReport")
            </div>
        </div>
        <div class="clr">
        </div>
    </div>
    <div class="b" id="bottom">
        <div class="b">
            <div class="b">
            </div>
        </div>
    </div>
</div>
<div id="clr_End" class="clr">
</div>
<script type="text/javascript">    
    function loadReport() {
        $("#dvLoader").css("display", "block");
        if('@Session["Admin"]'==null)
        {
        location.href='../Default/LogOut';
        }
       // loadOpenInvoices();
    $('#PartialContent').load('@Url.Action("PartialSalesReport", "Office")', {
            Month: $("#ddlMonth").val(),
            Year: $("#ddlYear").val(),
            ReferenceNo: $("#ddlCompanyReferenceNo").val(),
            CompanyUserId: $("#ddlUsers").val(),
            LocationId: $("#ddlLocation").val(),
            SalesRep: $("#ddlAccountManager").val(),
            CompanyId: $("#ddlCompany").val(),
            Status: $("#ddlStatus").val()
        },
        function (responseText, textStatus, XMLHttpRequest) {
            if (textStatus == "success") {
                $("#dvLoader").css("display", "none");
                //alert("hi");
            }
            if (textStatus == "error") {
               // alert("error");
            }
        });
    }
</script>